FROM golang:1.25.5-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o myapp ./cmd/api/main.go

FROM alpine

WORKDIR /app

# Copy the binary
COPY --from=builder /app/myapp .

# Copy the migrations folder
COPY --from=builder /app/database ./database

EXPOSE 8080

ENTRYPOINT ["./myapp"]

